### ISSUE TITLE
Command raised an exception: ZeroConnectedNodes: 

### ISSUE THREAD

**Issue by shuu-hackerman** [Darkempire78/Music-Discord-Bot#18]
Its return a error in Discord Channel when i put any Yt,Spotify or other link on my command Play.

[Command raised an exception: ZeroConnectedNodes: ]

I Have everything running great in MySQL. I think its some problem with youtubedl

**Comment by Darkempire78** [comment]
Show me the all console please. It must be an issue with Lavalink

**Comment by timo-y** [comment]
Hey, I'm having the same issue. The container-log is the following:

`WEBSOCKET | Connection Failure:: Cannot connect to host lavalink:2333 ssl:default [Connect call failed ('172.19.0.3', 2333)]

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection

return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection

raise exceptions[0]

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection

sock = await self._connect_sock(

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock

await self.sock_connect(sock, address)

File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect

return await fut

File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb

raise OSError(err, f'Connect call failed {address}')

ConnectionRefusedError: [Errno 111] Connect call failed ('172.19.0.3', 2333)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/wavelink/websocket.py", line 76, in _connect

self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)

File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 754, in _ws_connect

resp = await self.request(

File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request

conn = await self._connector.connect(

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect

proto = await self._create_connection(req, traces, timeout)

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection

_, proto = await self._create_direct_connection(req, traces, timeout)

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection

raise last_exc

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection

transp, proto = await self._wrap_create_connection(

File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection

raise client_error(req.connection_key, exc) from exc

aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lavalink:2333 ssl:default [Connect call failed ('172.19.0.3', 2333)]`

**Comment by danleitch** [comment]
I have the same issue 
<img width="359" alt="image" src="https://github.com/Darkempire78/Music-Discord-Bot/assets/40886941/f29ffba1-06a6-43e6-937a-f2a959caca66">

```
Playlist limit set to 15
Database check
* Soya Server (457597970376818689) added
* Leechie Collective (945238363668111420) added
----------------------------
We have logged in as MusicMonkey#3840
1.7.3
WEBSOCKET | Connection Failure:: Cannot connect to host lavalink:2333 ssl:default [Connect call failed ('172.19.0.3', 2333)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.19.0.3', 2333)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wavelink/websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lavalink:2333 ssl:default [Connect call failed ('172.19.0.3', 2333)]
```
